### ISSUE TITLE
Leacoin Constantly Forking

### ISSUE THREAD

**Issue by daygle** [leacoin/LeaCoin#2]
We run a mining pool dedicated to Leacoin and have noticed that Leacoin is constantly forking lately.

Just wondering if this coin is under attack or if you are aware of any issues.

Will there be a fix to combat these forks?

**Comment by leacoin** [comment]
Hello!

In order to avoid forking please make sure your firewall rules allow incoming connections to wallet's p2p port without any restrictions, and that you are not restricting the total number of connections in your config file too much. If tjat doesn't solve it, try configuring your wallet to connect only to nodes listed in the DNS A record set for the hostname "dnsseed.leacoin.org".

Please give us a feedback on this matter wjen you have any news.
